In [6]:
# Import the dependencies.
from pathlib import Path
import pandas as pd

In [ ]:
#reading the file in the old pandas way
main = Path("main_table.csv")
# main = Path("../../../data/departments.csv")
main_df = pd.read_csv(main)
main_df.head()

  dept_no        dept_name
0    d001        Marketing
1    d002          Finance
2    d003  Human Resources
3    d004       Production
4    d005      Development

Question 3 table output

In [ ]:
q3 = Path("Question_3_table.csv")
q3_df = pd.read_csv(q3)
q3_df.head()

     title dept_no        dept_name  emp_no     last_name first_name
0  Manager    d001        Marketing  110022    Markovitch  Margareta
1  Manager    d001        Marketing  110039      Minakawa   Vishwani
2  Manager    d002          Finance  110085         Alpin       Ebru
3  Manager    d002          Finance  110114    Legleitner      Isamu
4  Manager    d003  Human Resources  110183  Ossenbruggen    Shirish

Question 4 table output

In [ ]:
q4 = Path("Question_4_table.csv")
q4_df = pd.read_csv(q4)
q4_df.head()

  dept_no  emp_no last_name first_name           dept_name
0    d005   10001   Facello     Georgi         Development
1    d003   10005  Maliniak    Kyoichi     Human Resources
2    d004   10010  Piveteau  Duangkaew          Production
3    d006   10010  Piveteau  Duangkaew  Quality Management
4    d009   10011     Sluis       Mary    Customer Service

Question 6 table output

In [ ]:
q6 = Path("Question_6_table.csv")
q6_df = pd.read_csv(q6)
q6_df.head()

  dept_name  emp_no last_name first_name
0     Sales  211383    Candan        Uli
1     Sales  496429    Luders   Takanari
2     Sales  219797   Demeyer     Neelam
3     Sales  426193    Rattan     Huiqun
4     Sales   78524      Bahk     Zhiwei

Question 7 table output

In [ ]:
q7 = Path("Question_7_table.csv")
q7_df = pd.read_csv(q7)
q7_df.head()

   emp_no        last_name first_name    dept_name
0   98882  Vanwelkenhuysen     Yishay  Development
1   78316           Rahimi    Roselyn  Development
2  401368            Azumi      Vidar  Development
3  211383           Candan        Uli        Sales
4  496429           Luders   Takanari        Sales