In [9]:
from pathlib import Path
import pandas as pd

In [ ]:
main = Path("main_table.csv")
# main = Path("../../data/titles.csv")
main_df = pd.read_csv(main)
main_df.head()

  title_id               title
0    s0001               Staff
1    s0002        Senior Staff
2    e0001  Assistant Engineer
3    e0002            Engineer
4    e0003     Senior Engineer

Question 4 table output

In [11]:
q3 = Path("Question_3_table.csv")
q3_df = pd.read_csv(q3)
q3_df.head()

     title dept_no        dept_name  emp_no     last_name first_name
0  Manager    d001        Marketing  110022    Markovitch  Margareta
1  Manager    d001        Marketing  110039      Minakawa   Vishwani
2  Manager    d002          Finance  110085         Alpin       Ebru
3  Manager    d002          Finance  110114    Legleitner      Isamu
4  Manager    d003  Human Resources  110183  Ossenbruggen    Shirish