In [1]:
from pathlib import Path
import pandas as pd

In [2]:
main = Path("main_table.csv")
# main = Path("../../data/employees.csv")
main_df = pd.read_csv(main)
main_df.head()

   emp_no emp_title_id  birth_date  first_name  last_name sex   hire_date
0  473302        s0001  1953-07-25    Hideyuki   Zallocco   M  1990-04-28
1  475053        e0002  1954-11-18       Byong  Delgrande   F  1991-09-07
2   57444        e0002  1958-01-30       Berry       Babb   F  1992-03-21
3  421786        s0001  1957-09-28       Xiong   Verhoeff   M  1987-11-26
4  282238        e0003  1952-10-28  Abdelkader    Baumann   F  1991-01-18

Question 1 table output

In [6]:
q1 = Path("Question_1_table.csv")
q1_df = pd.read_csv(q1)
q1_df.head()

   emp_no  last_name first_name sex  salary
0   57444       Babb      Berry   F   48973
1  263976   Cusworth       Eran   M   40000
2  461591   Samarati     Xudong   M   40000
3  477657  Magliocco     Lihong   M   54816
4   29920      Tyugu    Shuichi   F   40000

Question 2 table output

In [7]:
q2 = Path("Question_2_table.csv")
q2_df = pd.read_csv(q2)
q2_df.head()

  first_name last_name   hire_date
0       Eran  Cusworth  1986-11-14
1      Bojan  Zallocco  1986-10-14
2      Nevio    Demizu  1986-05-18
3       Ziva    Vecchi  1986-07-03
4      Mohit     Speek  1986-01-14

Question 3 table output

In [8]:
q3 = Path("Question_3_table.csv")
q3_df = pd.read_csv(q3)
q3_df.head()

     title dept_no        dept_name  emp_no     last_name first_name
0  Manager    d001        Marketing  110022    Markovitch  Margareta
1  Manager    d001        Marketing  110039      Minakawa   Vishwani
2  Manager    d002          Finance  110085         Alpin       Ebru
3  Manager    d002          Finance  110114    Legleitner      Isamu
4  Manager    d003  Human Resources  110183  Ossenbruggen    Shirish

Question 4 table output

In [9]:
q4 = Path("Question_4_table.csv")
q4_df = pd.read_csv(q4)
q4_df.head()

  dept_no  emp_no last_name first_name           dept_name
0    d005   10001   Facello     Georgi         Development
1    d003   10005  Maliniak    Kyoichi     Human Resources
2    d004   10010  Piveteau  Duangkaew          Production
3    d006   10010  Piveteau  Duangkaew  Quality Management
4    d009   10011     Sluis       Mary    Customer Service

Question 5 table output

In [10]:
q5 = Path("Question_5_table.csv")
q5_df = pd.read_csv(q5)
q5_df.head()

  first_name  last_name sex
0   Hercules       Baer   M
1   Hercules      Biron   F
2   Hercules      Birge   F
3   Hercules    Berstel   F
4   Hercules  Bernatsky   M

Question 6 table output

In [11]:
q6 = Path("Question_6_table.csv")
q6_df = pd.read_csv(q6)
q6_df.head()

  dept_name  emp_no last_name first_name
0     Sales  211383    Candan        Uli
1     Sales  496429    Luders   Takanari
2     Sales  219797   Demeyer     Neelam
3     Sales  426193    Rattan     Huiqun
4     Sales   78524      Bahk     Zhiwei

Question 7 table output

In [12]:
q7 = Path("Question_7_table.csv")
q7_df = pd.read_csv(q7)
q7_df.head()

   emp_no        last_name first_name    dept_name
0   98882  Vanwelkenhuysen     Yishay  Development
1   78316           Rahimi    Roselyn  Development
2  401368            Azumi      Vidar  Development
3  211383           Candan        Uli        Sales
4  496429           Luders   Takanari        Sales

Question 8 table output

In [13]:
q8 = Path("Question_8_table.csv")
q8_df = pd.read_csv(q8)
q8_df.head()

  last_name  count
0      Baba    226
1     Coorg    223
2    Gelosh    223
3    Farris    222
4   Sudbeck    222