In [7]:
from pathlib import Path
import pandas as pd

In [ ]:
main = Path("main_table.csv")
# main = Path("../../data/salaries.csv")
main_df = pd.read_csv(main)
main_df.head()

   emp_no  salary
0   10001   60117
1   10002   65828
2   10003   40006
3   10004   40054
4   10005   78228

Question 1 table output

In [9]:
q1 = Path("Question_1_table.csv")
q1_df = pd.read_csv(q1)
q1_df.head()

   emp_no  last_name first_name sex  salary
0   57444       Babb      Berry   F   48973
1  263976   Cusworth       Eran   M   40000
2  461591   Samarati     Xudong   M   40000
3  477657  Magliocco     Lihong   M   54816
4   29920      Tyugu    Shuichi   F   40000